/* Poly Concreting — services page content */
window.PC_SERVICES = [

  /* 01 ── DRIVEWAYS ───────────────────────────────────────────────── */
  {
    id:"driveways", name:"Driveways", short:"Driveways",
    metaDesc:"Concrete driveways across South East QLD. Exposed aggregate, coloured & broom finish. Owner-operated, fixed price, same-day quotes. Based in Morayfield.",
    tag:"The first thing visitors see — and the last thing you want to redo.",
    hero:"assets/img/optimized/photos-driveways-plain4.webp", pos:"center 58%",
    intro:"A driveway carries real load, sheds water and sets the tone for the whole property. We prepare the base right, reinforce it properly and finish it to last decades — not seasons.",
    benefits:[
      {icon:"truck",    t:"Built for real loads",    d:"Correct thickness and steel for cars, caravans and the occasional concrete truck — no hairline cracking by winter."},
      {icon:"path",     t:"Drainage done right",     d:"Graded falls and crossfall so water runs off, not toward your garage or footings."},
      {icon:"sparkle",  t:"Any finish you like",     d:"Plain, broom, coloured or exposed aggregate — matched to your home and street appeal."},
      {icon:"check",    t:"Clean crossover & edges", d:"Tidy council-spec crossover and crisp cut-joints that keep the slab controlled and sharp."},
    ],
    gallery:["assets/img/agg-driveway.webp","assets/img/agg-joint.webp","assets/img/agg-river-stone.webp"],
    steps:[
      {t:"Set-out & excavate",  d:"Mark falls, strip to subgrade and compact a stable base."},
      {t:"Form & reinforce",    d:"Box up the edges, lay steel mesh on chairs to the correct cover depth."},
      {t:"Pour & finish",       d:"Place, screed and bring up your chosen finish in one continuous pour."},
      {t:"Cut, cure & seal",    d:"Saw control joints, cure properly and seal to lock in the colour."},
    ],
    faqs:[
      {q:"How long until I can drive on it?",    a:"Light foot traffic in 24 hours, vehicles after about 7 days. We'll give you exact dates for your mix and the weather."},
      {q:"Will it crack?",                        a:"All concrete moves — that's why we reinforce and saw-cut control joints. Done right, cracking is controlled and stays in the joints."},
      {q:"Can you match my existing driveway?",  a:"Usually yes. We colour-match and replicate finishes; we'll be honest if a clean tie-in isn't achievable."},
    ],
    stat:["80–250m²","7-day cure","Fixed quote"],
    testimonial:{ q:"The exposed aggregate driveway is flawless two winters on. They sent a photo update every single day.", n:"Sarah & Tom H.", r:"Bahr Scrubs" },
  },

  /* 02 ── SLABS ───────────────────────────────────────────────────── */
  {
    id:"slabs", name:"House & Shed Slabs", short:"Slabs",
    metaDesc:"House & shed slabs across South East QLD. Reinforced, correctly prepared and builder-ready. Acreage & sloping sites welcome. Fixed price. Based in Morayfield.",
    headline:["The slab", "everything sits on."],
    tag:"The foundation everything else sits on. Built right, not eyeballed.",
    hero:"assets/img/optimized/photos-trowel-slab1.webp", pos:"center",
    intro:"A slab is only as good as the prep underneath it. We get the steel, levels and falls right and pour a flat, true slab your builder can hand straight to the next trade.",
    mistakes:[
      { icon:"slab",  prob:"Steel on the ground, not in it",       probD:"Mesh flat on the ground gives almost no structural benefit. The steel needs to be at mid-height on chairs — that's what stops cracking under load for the next 30 years.",      fixD:"Mesh on chairs to the correct cover depth, every pour. We don't cut corners on the one thing that determines how the slab performs." },
      { icon:"path",  prob:"No drainage plan",                      probD:"A slab poured without positive falls drains toward your footings and under your walls. By the time you see the problem, the damage is already done.",                             fixD:"We set grades before formwork goes up — water runs the way we tell it to, away from everything it shouldn't touch." },
      { icon:"truck", prob:"Wrong concrete spec",                   probD:"Ordering the cheapest mix to save $100 on a 200m² slab is a false economy. Under-specified concrete fails faster, loses surface strength and can't be fixed.",                  fixD:"We specify the right mix for the application — shed floor, garage or living area — and we document the slump on delivery." },
    ],
    benefits:[
      {icon:"clipboard", t:"To your slab design",   d:"Soil prep, footings and steel correctly placed to your slab plan."},
      {icon:"slab",      t:"Flat and true",          d:"Screeded and floated to tight tolerances so walls and floors land right."},
      {icon:"truck",     t:"Any site, any access",   d:"Acreage, sloping or tight blocks — we sort access, fill and compaction first."},
      {icon:"check",     t:"On the builder's program", d:"We sequence around your trades and hit the date so the build keeps moving."},
    ],
    gallery:["assets/img/slab-bush-finished.webp","assets/img/slab-reo-bush.webp","assets/img/pour-reo.webp"],
    steps:[
      {t:"Site prep & fill",     d:"Cut, fill and compact the pad; set out to the slab plan."},
      {t:"Formwork & plumbing",  d:"Box the edges, install pods and let plumbers rough in."},
      {t:"Steel & inspection",   d:"Lay reinforcement to the correct cover, ready for certifier sign-off."},
      {t:"Pour & cure",          d:"Place, vibrate, float and cure the slab to strength."},
    ],
    pricingFactors:[
      { icon:"slab",    t:"Size & thickness",      d:"Larger pours spread fixed costs. Thickness varies by use — a shed floor needs less than a garage taking vehicle loads." },
      { icon:"truck",   t:"Reinforcement spec",     d:"SL72, SL82 or engineered reo — the spec depends on soil class and load. We assess and advise before quoting." },
      { icon:"path",    t:"Site preparation",       d:"Cut, fill and compaction costs vary with conditions. A level block with easy access is cheaper than a sloped site." },
      { icon:"sparkle", t:"Finish choice",          d:"Power float is the base for most slabs. Exposed, coloured or broom adds cost — itemised clearly in the quote." },
    ],
    faqs:[
      {q:"Do you do acreage and sloping blocks?",  a:"Constantly. Cut-and-fill and drop-edge beams on sloping sites are our bread and butter across SEQ."},
      {q:"Can you work with my builder?",          a:"Yes — we slot into the build program and coordinate with your other trades and certifier."},
      {q:"Shed slabs too?",                        a:"Absolutely — machinery sheds, garages and granny flats, sized and reinforced for the load."},
    ],
    stat:["Reinforced","Slab-ready","Builder-ready"],
    testimonial:{ q:"We sequenced Poly around 14 trades on a live site and they never lost a day. Spotless at handover.", n:"Daniel R.", r:"Mount Mee" },
  },

  /* 03 ── PATHWAYS ────────────────────────────────────────────────── */
  {
    id:"pathways", name:"Pathways", short:"Pathways",
    metaDesc:"Concrete pathways & side access across South East QLD. Graded falls, channel drains, broom or exposed aggregate. Owner-operated, fixed price. Based in Morayfield.",
    headline:["Paths that drain,", "last and look right."],
    tag:"Side access, wrap-arounds and connections that actually drain.",
    hero:"assets/img/path-side-drain.webp", pos:"center 55%",
    intro:"Paths look simple and trip people up most when done badly. We get the falls, joints and edges right so your path stays level, dry and crack-free — even down the tight side of the house.",
    mistakes:[
      { icon:"path",  prob:"No crossfall",          probD:"A path poured dead flat ponds water against the house, gates and fences. Wet season turns it into a river down the side of your home.",             fixD:"Every path we pour has a positive crossfall built in. Water runs away from the house — not along the wall or under the door." },
      { icon:"check", prob:"Bad edge treatment",    probD:"Paths that end without a properly formed edge crack, spall and look rough within two wet seasons — especially against fences and service boxes.",     fixD:"Clean formed edges every time, including the awkward bits against brickwork, fences and drainage boxes." },
      { icon:"slab",  prob:"Cut joints skipped",    probD:"Concrete shrinks as it cures. Without joints in the right places the slab cracks where it wants to — usually somewhere highly visible.",             fixD:"We cut joints at the correct spacing before the concrete fully cures, controlling where any movement happens." },
    ],
    benefits:[
      {icon:"path",    t:"Falls that work",       d:"Water runs away from the house, with channel drains where the site needs them."},
      {icon:"check",   t:"Tidy in tight spots",   d:"Clean hand-finished edges against brick, fences and service boxes."},
      {icon:"sparkle", t:"Match the house",        d:"Broom, coloured or exposed aggregate to suit the rest of your concrete."},
      {icon:"trowel",  t:"Trip-free joins",        d:"Level transitions at doors, gates and existing paths — no lips to catch."},
    ],
    gallery:["assets/img/path-side-drain.webp","assets/img/agg-path-brick.webp","assets/img/path-gas.webp"],
    steps:[
      {t:"Set the line & falls",  d:"String the path, set width and crossfall for drainage."},
      {t:"Prep & form",           d:"Excavate, compact and form the edges around obstacles."},
      {t:"Pour & finish",         d:"Place and finish to your chosen surface in one run."},
      {t:"Joint & clean up",      d:"Cut joints, strip forms and leave the site tidy."},
    ],
    pricingFactors:[
      { icon:"path",    t:"Length & width",   d:"Narrow side paths are priced per linear metre. Wide feature paths and wrap-arounds are priced per m² — we use whichever suits the job." },
      { icon:"truck",   t:"Site access",      d:"Paths beside the house often need barrow or pump access. That affects labour time — we walk the site before quoting." },
      { icon:"sparkle", t:"Drainage",         d:"Standard crossfall is included. Channel drains and pit connections are scoped and priced separately." },
      { icon:"slab",    t:"Finish choice",    d:"Broom is the base rate. Exposed aggregate or colour adds material and labour — itemised clearly in the quote." },
    ],
    faqs:[
      {q:"Can you fit down a narrow side access?",  a:"Yes — tight side runs with drainage are one of our most common jobs. We barrow or pump where machines won't fit."},
      {q:"Will it pond or pool water?",             a:"No — we build positive falls and add channel drains where the ground works against you."},
      {q:"Can you add drainage?",                   a:"We install strip and channel drains tied into your stormwater as part of the path."},
    ],
    stat:["Graded falls","Channel drains","Tidy edges"],
    testimonial:{ q:"They poured the tight side of the house and added a channel drain — bone dry through the wet season now.", n:"Priya N.", r:"Caboolture" },
  },

  /* 04 ── OUTDOOR ENTERTAINING ────────────────────────────────────── */
  {
    id:"patios", name:"Outdoor Entertaining", short:"Outdoor",
    metaDesc:"Outdoor entertaining slabs across South East QLD. Level, shaped & finished for QLD weather. Broom, coloured or exposed aggregate. Fixed price. Based in Morayfield.",
    headline:["The floor your", "outdoor space deserves."],
    tag:"Alfresco floors and entertaining areas built to live on.",
    hero:"assets/img/patio-broom.webp", pos:"center 55%",
    intro:"Outdoor living starts with the floor. Whether it's under the patio roof or out in the open, we pour level, good-looking slabs shaped to your space and finished to handle Queensland weather.",
    mistakes:[
      { icon:"slab",    prob:"Not level enough for furniture",   probD:"Outdoor furniture on a wavy slab rocks, wobbles and eventually gets shimmed with cardboard. A bad screed looks cheap and ages badly.",                                  fixD:"We screed to a tight tolerance — flat enough for furniture, still graded enough to drain. Both, not one or the other." },
      { icon:"path",    prob:"Water sitting on the slab",        probD:"An entertaining area that puddles after rain isn't pleasant. Without falls, water sits — and in Queensland that's a slip hazard and a mould risk under the roof.",     fixD:"Falls are set before formwork goes up. Drainage direction is designed into the job — not sorted after the pour." },
      { icon:"sparkle", prob:"Wrong finish for outdoors",        probD:"A power-floated patio looks great until the first wet afternoon when it's slick under bare feet. Outdoor finishes must perform when wet.",                             fixD:"We match the finish to how the space is used — broom, exposed or textured for outdoor areas. Never smooth where grip matters." },
    ],
    benefits:[
      {icon:"check",   t:"Level & true",       d:"A flat floor for furniture, outdoor kitchens and entertaining."},
      {icon:"sparkle", t:"Finish to suit",      d:"Broom, coloured, decorative or exposed — your call."},
      {icon:"path",    t:"Shaped to the space", d:"Curved or angled edges that follow the garden and roofline."},
      {icon:"trowel",  t:"Tied to the house",   d:"Clean junctions at doors, posts and existing slabs."},
    ],
    gallery:["assets/img/patio-broom.webp","assets/img/agg-patio-curve.webp","assets/img/path-posts.webp"],
    steps:[
      {t:"Plan the area",   d:"Set the shape, levels and fall for the space."},
      {t:"Prep & form",     d:"Excavate, compact and form curved or square edges."},
      {t:"Pour & finish",   d:"Place and finish to your chosen surface."},
      {t:"Seal & clean up", d:"Seal where needed and leave it ready to furnish."},
    ],
    pricingFactors:[
      { icon:"slab",    t:"Size & shape",            d:"Square metres is the base rate driver. Curves, islands and complex formwork shapes add labour — we price the actual layout." },
      { icon:"sparkle", t:"Finish choice",            d:"Broom is the base rate. Exposed aggregate, colour and decorative finishes are itemised separately so you know exactly what you're paying for." },
      { icon:"path",    t:"Drainage & falls",         d:"Standard crossfall is included. Channel drains, step-downs and stormwater connections are scoped and priced separately." },
      { icon:"truck",   t:"Site access & prep",       d:"Easy truck access keeps costs down. Steps, gates and tight access may require pump or barrow — we confirm before quoting." },
    ],
    faqs:[
      {q:"Can you pour around posts and existing structures?",  a:"Yes — we box neatly around posts, drains and walls for a tidy, integrated finish."},
      {q:"Curved edges?",                                       a:"No problem. Curved and angled patios that follow your garden are some of our favourites."},
      {q:"Can you match my indoor floor?",                      a:"We can colour and finish to complement your interior and existing outdoor areas."},
    ],
    stat:["Any shape","Weather-ready","Furnish-ready"],
    testimonial:{ q:"The curved alfresco slab is the best part of the yard now. Sealed up beautifully and dead level.", n:"Josh & Amara T.", r:"The Gap" },
  },

  /* 05 ── POOL SURROUNDS ──────────────────────────────────────────── */
  {
    id:"pools", name:"Pool Surrounds", short:"Pool Surrounds",
    metaDesc:"Concrete pool surrounds across South East QLD. Slip-rated finishes, channel drainage & clean coping. Owner-operated, fixed price. Based in Morayfield.",
    headline:["Concrete that handles", "the wet zone."],
    tag:"Slip-safe, cool underfoot, and finished to frame the water.",
    hero:"assets/img/pool-coping.webp", pos:"center",
    intro:"A pool surround has to look the part and stay safe when wet. We build slip-resistant surrounds with proper falls and clean coping that ties the pool, paving and house together.",
    mistakes:[
      { icon:"sparkle", prob:"No slip rating",                   probD:"A smooth or lightly broomed pool surround is a genuine slip hazard when wet — especially with kids running. It's also a liability issue.",                             fixD:"Every pool surround we pour gets a slip-rated finish appropriate for the wet zone. We won't pour a smooth slab around a pool." },
      { icon:"path",    prob:"Drainage not designed in",         probD:"Surrounds without channel drainage flood in the wet season and hold standing water around the pool — exactly where you don't want it.",                              fixD:"Channel drains sized for the area and connected to stormwater. Water off the slab fast — not pooling at feet or running into the pool." },
      { icon:"slab",    prob:"Coping joins done as an afterthought", probD:"A surround poured without coordinating the coping tie-in looks patchy and lets water underneath. Most problems show up right at the edge.",                        fixD:"We coordinate the pour to tie cleanly into coping — a seamless, watertight join at the most vulnerable point." },
    ],
    benefits:[
      {icon:"path",    t:"Slip-resistant",   d:"Exposed aggregate and textured finishes that grip wet feet."},
      {icon:"check",   t:"Coping done clean", d:"Bullnose and drop-edge coping that frames the pool sharply."},
      {icon:"sparkle", t:"Cooler finishes",   d:"Lighter colours and textures that don't bake underfoot in summer."},
      {icon:"trowel",  t:"Falls & drainage",  d:"Surrounds graded away from the pool and house, with drains where needed."},
    ],
    gallery:["assets/img/pool-coping.webp","assets/img/pool-surround.webp","assets/img/pool-deck-tile.webp"],
    steps:[
      {t:"Plan around the pool", d:"Set levels, coping line and falls around the shell."},
      {t:"Form & reinforce",     d:"Box up, reinforce and prep for a clean coping detail."},
      {t:"Pour & finish",        d:"Place and bring up a slip-safe finish to your choice."},
      {t:"Seal & detail",        d:"Seal, set coping and tie into fencing and paving."},
    ],
    pricingFactors:[
      { icon:"slab",    t:"Pool perimeter & shape", d:"Freeform and curved pools require more formwork time than rectangular layouts. We price the actual shape — not a rectangle." },
      { icon:"path",    t:"Drainage requirements",  d:"Channel drain sizing and stormwater connections vary with the area and site conditions. A drainage plan is included in every quote." },
      { icon:"sparkle", t:"Finish choice",           d:"Slip-rated broom is the base rate. Exposed aggregate, colour and decorative finishes are itemised separately." },
      { icon:"truck",   t:"Coping & tie-ins",        d:"Integrating with existing coping or coordinating new coping and fencing takes site assessment. We scope this before we quote." },
    ],
    faqs:[
      {q:"What finish is best around a pool?",    a:"Exposed aggregate or a textured decorative finish — both grip when wet and shrug off splash-out and sunscreen."},
      {q:"Can you work with my pool builder?",    a:"Yes, we coordinate timing so the surround goes down at the right stage of the pool build."},
      {q:"Will it get too hot?",                  a:"We steer you to lighter, textured finishes that stay far cooler than dark pavers."},
    ],
    stat:["Slip-rated","Clean coping","Cooler finish"],
    testimonial:{ q:"Coping and surround came up immaculate and it's never slippery — exactly what we wanted for the kids.", n:"The Williams Family", r:"Wavell Heights" },
  },

  /* 06 ── SMALL COMMERCIAL CONCRETE ──────────────────────────────── */
  {
    id:"commercial", name:"Small Commercial", short:"Commercial",
    metaDesc:"Small commercial concrete across South East QLD — shopfront slabs, hardstand, parking bays. Fixed price, fixed date. QBCC licensed, fully insured. Based in Morayfield.",
    headline:["Built to", "your program."],
    tag:"Shopfront floors, hardstand and parking bays — fixed price, fixed date, documentation supplied. Never holding up your trades.",
    hero:"assets/img/optimized/photos-trowel-slab2.webp", pos:"center 55%",
    intro:"Commercial concrete has one rule residential doesn't: the program. Your builder, your certifier, your fit-out team — they're all waiting for the slab to be ready. We quote a locked price, commit to a pour date and supply the documentation your certifier needs. The site gets handed back clean so the next trade can walk straight on.",
    mistakes:[
      { icon:"comm",  prob:"Contractor misses the program date",    probD:"Your fit-out team is booked, your certifier is scheduled and your opening date is locked. A concreter who can't commit to a pour date cascades those costs straight to you.",      fixD:"We give you a pour date in writing and we hold it. If site conditions change, you hear from us immediately — not when you call to check." },
      { icon:"slab",  prob:"Slab not flat enough for fit-out",      probD:"Racking, tiling and floor coverings all have tolerance requirements. A slab poured without laser control fails those checks and triggers rectification costs before fit-out even starts.",  fixD:"Power-floated to ±3mm over 3m as standard. We bring the levels equipment, not the estimations." },
      { icon:"clipboard", prob:"No documentation at handover",      probD:"Certifiers and body corporates increasingly require concrete pour records — slump, batch tickets, pour time. A contractor who doesn't document leaves you holding the compliance gap.",      fixD:"Slump tests, batch tickets and pour records supplied at handover. Everything your certifier needs, ready to file." },
    ],
    benefits:[
      {icon:"clipboard", t:"Fixed price, fixed date",         d:"Locked in writing before we start. No variations unless scope changes — and we tell you before we proceed, not after."},
      {icon:"slab",      t:"Power-floated to tolerance",      d:"Laser-levelled and floated to ±3mm over 3m. Suitable for racking, tiling, floor coverings and foot traffic from day one."},
      {icon:"truck",     t:"Documentation at handover",       d:"Slump tests, batch tickets and pour records supplied. Everything your certifier or body corporate needs, ready to file."},
      {icon:"check",     t:"After-hours & weekend pours",     d:"We work around your trading hours and your builder's program. Weekend and after-hours pours so your business keeps running."},
    ],
    gallery:["assets/video/com1.mp4","assets/img/slab-powerfloat.webp","assets/img/slab-float-bush.webp"],
    steps:[
      {t:"Site visit & scope",       d:"Confirm dimensions, finish spec, access and the pour date that fits your builder's program."},
      {t:"Fixed quote issued",       d:"Locked price and date in writing — no provisional sums, no surprises at invoice."},
      {t:"Prep & reinforce",         d:"Sub-base, membrane and steel placed to the correct spec for the load and use."},
      {t:"Pour, float & document",   d:"Power-float to tolerance. Slump tests taken, batch tickets kept, pour time recorded."},
      {t:"Cut, cure & hand over",    d:"Saw joints placed, curing compound applied, site cleaned. Ready for the next trade."},
    ],
    faqs:[
      {q:"Can you commit to a specific pour date?",     a:"Yes — we give you a pour date in writing and we hold it. If site conditions force a change, you hear from us immediately so you can adjust your program."},
      {q:"What documentation do you supply?",           a:"Slump test records, batch delivery tickets and pour time logs at handover. If your certifier or body corporate has specific requirements, let us know upfront and we'll format accordingly."},
      {q:"Can you pour after hours or on weekends?",    a:"Yes. Weekend and after-hours pours so your shopfront, premises or development keeps moving on schedule."},
      {q:"What size commercial jobs do you take on?",   a:"Shopfront floors, unit slabs, parking bays, hardstand and small commercial builds. We focus on the work we do best and quote honestly on everything else."},
      {q:"Are you licensed and insured for commercial?", a:"QBCC licensed (15393395) and fully insured for commercial work across SEQ. Certificates of currency available on request."},
    ],
    stat:["QBCC Licensed","Fixed price & date","Documentation supplied"],
    testimonial:{ q:"Poured our shopfront slab over a weekend so we opened on time. Numbers landed exactly where quoted.", n:"Priya N.", r:"Narangba — Commercial Client" },
  },

  /* 07 ── RESURFACING ─────────────────────────────────────────────── */
  {
    id:"resurfacing", name:"Resurfacing", short:"Resurfacing",
    metaDesc:"Concrete resurfacing across South East QLD. Bonded overlay for worn or tired slabs — no demolition. Dulux Avista colours & finishes. Fixed price. Based in Morayfield.",
    tag:"Refresh worn, stained or tired concrete — without the cost of a full replacement.",
    hero:"assets/img/covercrete-hero.webp", pos:"center",
    intro:"Your existing slab is probably structurally fine — it just doesn't look it. A polymer-modified overlay bonds directly to sound concrete and gives you a fresh, sealed surface in the full Dulux Avista colour and stencil range. No demolition. No skip bin. Half the disruption of a full replacement.",
    benefits:[
      {icon:"clipboard", t:"Structure assessed first",     d:"We check the slab before we quote. If the base isn't sound, resurfacing won't last — we'll tell you that upfront."},
      {icon:"trowel",    t:"Bonded overlay",               d:"Polymer-modified topping bonds to the existing concrete and won't delaminate when the prep is done right."},
      {icon:"sparkle",   t:"Choice of finish",             d:"Smooth, broom, exposed or textured — the new surface can take most standard finishes."},
      {icon:"check",     t:"Fraction of replacement cost", d:"When the sub-base and structure are solid, resurfacing delivers a like-new result for significantly less."},
    ],
    gallery:["assets/img/slab-float-bush.webp","assets/img/place-broom.webp","assets/img/path-render.webp"],
    steps:[
      {t:"Assess the existing surface", d:"Check for delamination, sub-base movement or contamination before committing to a resurface."},
      {t:"Prepare & repair",            d:"Grind back the surface, fill cracks and fix any spalling so the overlay has a clean base to bond to."},
      {t:"Apply the overlay",           d:"Trowel or spray the bonded topping to the correct and consistent thickness."},
      {t:"Finish, cure & seal",         d:"Bring up the chosen texture, cure properly and seal to protect against water and UV."},
    ],
    faqs:[
      {q:"How do I know if mine can be resurfaced?", a:"If the slab is structurally sound and the sub-base isn't moving, resurfacing is usually viable. We assess it before we quote anything."},
      {q:"How thick is the new layer?",              a:"Typically 6–12mm depending on the condition of the existing surface and the finish specified."},
      {q:"Can you match the existing finish?",       a:"Most common finishes — broom, exposed, smooth — are achievable in a resurface. We'll confirm before we start."},
    ],
    stat:["Bonded overlay","6–12mm topping","Assess before quoting"],
    testimonial:{ q:"They resurfaced our old driveway instead of replacing it — saved us a fortune and it looks better than it ever did.", n:"Michael F.", r:"Ipswich" },
  },

  /* ── STANDARD FINISHES ─────────────────────────────────────────── */

  /* 09 ── TROWEL FINISH ───────────────────────────────────────────── */
  {
    id:"trowel", name:"Trowel Finish", short:"Trowel Finish",
    metaDesc:"Trowel finish concrete across South East QLD. Steel-trowelled, hard & dense for indoor floors, garages & commercial slabs. Fixed price. Based in Morayfield.",
    tag:"A smooth, dense surface — the most versatile and the base for polished and sealed concrete.",
    hero:"assets/img/trowel-hero.webp", pos:"center",
    intro:"A steel-trowelled finish is worked after screeding to close the surface and produce a hard, smooth, dense slab. It's what goes under polished concrete, sealed floors and most commercial interiors — and it requires timing and skill to do consistently across a large pour.",
    benefits:[
      {icon:"slab",      t:"Hard & dense surface",     d:"Steel trowelling compacts the surface layer, producing a harder, more wear-resistant slab than a floated finish."},
      {icon:"sparkle",   t:"Base for any coating",     d:"Smooth trowel finish is the correct prep for epoxy coatings, sealers, polished concrete and overlays."},
      {icon:"trowel",    t:"Clean, seamless look",     d:"No texture, no drag marks — a flat, consistent surface that reads well in large open spaces."},
      {icon:"check",     t:"Timing matters",           d:"We work the surface in passes at the right stage — rushed or late trowelling shows up immediately."},
    ],
    gallery:["assets/img/trowel-IMG_0262.webp","assets/img/trowel-IMG_0263.webp","assets/img/trowel-IMG_9277.webp","assets/img/trowel-IMG_9284.webp","assets/img/trowel-IMG_9374.webp","assets/img/trowel-IMG_9513.webp"],
    steps:[
      {t:"Pour & screed",       d:"Place the concrete and screed to level, removing excess and setting the flat plane."},
      {t:"Bull-float",          d:"Long-handled float knocks down ridges and embeds aggregate below the surface."},
      {t:"First trowel pass",   d:"Hand or machine trowel once the bleed water has evaporated and the surface will bear weight."},
      {t:"Final pass & cure",   d:"Finish trowel pass to close the surface fully; cure with compound or wet hessian."},
    ],
    faqs:[
      {q:"Is a trowel finish slippery?",              a:"Can be when wet — it's typically used indoors or under cover. For outdoor or wet areas we recommend a broom, swirl or exposed finish instead."},
      {q:"Can it be polished later?",                 a:"Yes — a quality trowel finish is the starting point for grinding and polishing. The smoother and flatter it's laid, the better the polished result."},
      {q:"What's the difference between power-float and hand-trowel?",  a:"Power-float covers large areas faster; hand-trowelling is used for edges and for the final passes on high-spec floors. We use both."},
    ],
    stat:["Steel-trowelled","Hard & dense","Indoor & commercial"],
    testimonial:{ q:"The power-floated warehouse floor is still dead flat two years later — not a mark on it.", n:"Daniel R.", r:"Narangba" },
  },

  /* 10 ── BROOM FINISH ────────────────────────────────────────────── */
  {
    id:"broom", name:"Broom Finish", short:"Broom Finish",
    metaDesc:"Broom finish concrete across South East QLD. Slip-resistant, clean lines for driveways, paths & outdoor slabs. Owner-operated, fixed price. Based in Morayfield.",
    tag:"The most practical concrete finish — clean lines, solid grip, ages well.",
    hero:"assets/img/broom-hero.webp", pos:"center",
    intro:"Broom finish is applied by drawing a stiff brush across the surface of the concrete before it sets, leaving a series of parallel lines that add grip and a clean, uniform look. It's the most widely used outdoor finish for good reason — it works, it lasts and it suits almost every job.",
    benefits:[
      {icon:"path",      t:"Reliable slip-resistance",  d:"Broom lines give consistent grip underfoot, wet or dry — suitable for driveways, paths and outdoor slabs."},
      {icon:"check",     t:"Consistent & clean",        d:"Straight, parallel lines across the full slab — no patchwork, no variation in depth or spacing."},
      {icon:"slab",      t:"Suits any application",     d:"Driveways, paths, slabs, patios — broom finish is appropriate almost everywhere outdoors."},
      {icon:"sparkle",   t:"Pairs with colour",         d:"Add an oxide pigment and broom finish gives you a coloured slab that's practical and good-looking."},
    ],
    gallery:["assets/img/broom1.webp","assets/img/broom2.webp","assets/img/broom3.webp","assets/img/broom4.webp","assets/img/broom5.webp","assets/img/broom7.webp"],
    steps:[
      {t:"Pour & screed",    d:"Place and screed to level, setting the plane of the finished slab."},
      {t:"Float",            d:"Bull-float to consolidate the surface and remove excess bleed water."},
      {t:"Draw the broom",   d:"Pull the broom across the surface at the right consistency — too early and it smears, too late and it tears."},
      {t:"Cut & cure",       d:"Saw control joints at the correct spacing; cure to full strength before use."},
    ],
    faqs:[
      {q:"Which direction does the broom run?",    a:"Typically perpendicular to traffic flow so the lines give the most grip underfoot and to tyres."},
      {q:"How coarse is the texture?",             a:"We match the broom coarseness to the application — finer for paths and patios, coarser for driveways."},
      {q:"Can it be combined with coloured concrete?", a:"Yes — broom over oxide-coloured concrete is one of the most popular and cost-effective finish combinations we do."},
    ],
    stat:["Slip-resistant","Any outdoor area","Pairs with colour"],
    testimonial:{ q:"Just a straightforward backyard slab — but they did it exactly right. Level, no cracks, tidy edges. Exactly what we needed.", n:"Tony B.", r:"Morayfield" },
  },

  /* 11 ── SWIRL FINISH ────────────────────────────────────────────── */
  {
    id:"swirl", name:"Swirl Finish", short:"Swirl Finish",
    metaDesc:"Swirl finish concrete across South East QLD. Hand-applied circular texture for patios, pool surrounds & entertaining areas. Fixed price. Based in Morayfield.",
    tag:"Hand-trowelled circular texture — grip and character without going decorative.",
    hero:"assets/img/coloured5.webp", pos:"center",
    intro:"A swirl finish is applied by hand, working a steel trowel in overlapping arcs across the surface of the concrete. The result is a consistent circular texture that adds grip, breaks up flat light and gives concrete a crafted look — without the cost of exposed aggregate or stencil.",
    benefits:[
      {icon:"trowel",    t:"Applied by hand",          d:"Each swirl is worked in by a finisher — it's a skilled, time-on-the-slab finish, not a machine pass."},
      {icon:"path",      t:"Better grip than smooth",  d:"The circular texture adds slip-resistance, making it a practical choice for outdoor areas and pool surrounds."},
      {icon:"sparkle",   t:"Visual character",         d:"Swirl patterns catch light differently across the day and give a slab a quality, hand-crafted appearance."},
      {icon:"check",     t:"Works with colour",        d:"Combine with oxide pigments for a coloured swirl finish that adds warmth and depth to the surface."},
    ],
    gallery:["assets/img/coloured3.webp","assets/img/coloured6.webp","assets/img/coloured2.webp","assets/img/coloured1.webp"],
    steps:[
      {t:"Pour & screed",    d:"Place and screed the slab to level as normal."},
      {t:"Float the surface", d:"Bull-float and fresno to consolidate and flatten before finishing."},
      {t:"Work the swirls",  d:"Finisher works the steel trowel in overlapping arcs while the concrete is at the right stage."},
      {t:"Cure & seal",      d:"Apply curing compound and seal once the surface has hardened."},
    ],
    faqs:[
      {q:"Is the pattern consistent across the whole slab?",  a:"Yes — a good swirl finish is uniform in size and depth across the full area. Patchy swirls are a sign of a rushed or late finish."},
      {q:"Can you do it on large areas?",                     a:"Yes, though it takes more time per square metre than a broom finish. We factor that into the quote."},
      {q:"Does it suit driveways?",                          a:"It can, though broom finish is more common on driveways. Swirl is popular on patios, pool surrounds and under-cover entertaining areas."},
    ],
    stat:["Hand-applied","Slip-resistant","Outdoor & entertaining"],
    testimonial:{ q:"The swirl finish on the alfresco is a talking point every time someone visits. Really sets it apart from plain broom.", n:"Josh & Amara T.", r:"The Gap" },
  },

  /* ── DECORATIVE FINISHES ────────────────────────────────────────── */

  /* 12 ── EXPOSED AGGREGATE ───────────────────────────────────────── */
  {
    id:"exposed", name:"Exposed Aggregate", short:"Exposed Aggregate",
    metaDesc:"Exposed aggregate concrete across South East QLD. Boral & Nielsens ranges, wet-look sealed. Driveways, paths & pool surrounds. Fixed price. Based in Morayfield.",
    tag:"Our specialty. Stone you can feel underfoot, sealed to a wet-look shine.",
    hero:"assets/img/agg-river-stone.webp", pos:"center",
    intro:"Exposed aggregate is where craft shows. Wash back too early or too late and it's ruined — timing is everything. A decade-plus of pours means we get the reveal right, every time.",
    benefits:[
      {icon:"agg",     t:"Stone, your way",         d:"Salt & pepper, charcoal, river-stone or gold — choose your colour with confidence."},
      {icon:"sparkle", t:"Sealed wet-look",          d:"Multiple seal coats for that rich, just-wet finish that also locks out stains."},
      {icon:"path",    t:"Slip-resistant",           d:"Naturally textured — ideal around pools, paths and sloped driveways."},
      {icon:"check",   t:"Even, consistent reveal",  d:"Washed back to a uniform depth across the whole slab, not patchy in the corners."},
    ],
    gallery:["assets/img/exposed1.webp","assets/img/exposed2.webp","assets/img/exposed3.webp","assets/img/exposed4.webp"],
    galleryLabels:["Salt & Pepper — Boral","Night Sky — Boral","Salt & Pepper — Boral","Eclipse — Nielsens"],
    aggRanges:[
      {
        supplier:"Boral",
        intro:"Boral's Exposé range is the SEQ exposed aggregate standard — consistent sizing, reliable colour batching and wide availability. We pour Boral mixes regularly and know exactly how each colour washes back and seals up.",
        mixes:[
          { name:"Salt and Pepper", img:"assets/img/agg-boral/salt-and-pepper.webp", tone:"Black · White",         desc:"The classic. Fine black and white aggregate — clean, contemporary and the most popular choice for modern SEQ homes." },
          { name:"Pearl",           img:"assets/img/agg-boral/pearl.webp",           tone:"Cream · White",         desc:"Soft cream and off-white tones that keep the surface light and bright. A favourite for pool surrounds and alfresco areas." },
          { name:"Silver Frost",    img:"assets/img/agg-boral/silver-frost.webp",    tone:"Cool Silver · Grey",    desc:"Cool silver-grey aggregate with a frosted, clean finish. Works beautifully with rendered homes and Hamptons-style builds." },
          { name:"Arctic Sun",      img:"assets/img/agg-boral/arctic-sun.webp",      tone:"Warm White · Gold",     desc:"Light warm-white tones with subtle golden flecks — an elegant finish that catches the Queensland light." },
          { name:"River Red",       img:"assets/img/agg-boral/river-red.webp",       tone:"Warm Red · Terracotta", desc:"Earthy red and terracotta tones that complement brick, sandstone and traditional Queenslander homes." },
          { name:"Winter Red",      img:"assets/img/agg-boral/winter-red.webp",      tone:"Deep Red · Rust",       desc:"A richer, deeper red blend — bold and earthy. Makes a strong statement on driveways and entries." },
          { name:"Bengal",          img:"assets/img/agg-boral/bengal.webp",          tone:"Warm Brown · Gold",     desc:"Warm amber and golden-brown tones with natural variation. A rich, premium look suited to acreage and character homes." },
          { name:"Cherry Blossom",  img:"assets/img/agg-boral/cherry-blossom.webp",  tone:"Blush · Pink · Cream",  desc:"Soft pink and cream tones — a delicate, distinctive option for paths, pool surrounds and entertaining areas." },
          { name:"Spitfire",        img:"assets/img/agg-boral/spitfire.webp",        tone:"Mid Grey · Blue",       desc:"Cool mid-grey with subtle blue undertones. Strong and contemporary — pairs well with dark render and modern architecture." },
          { name:"Ocean Floor",     img:"assets/img/agg-boral/ocean-floor.webp",     tone:"Deep Blue · Grey",      desc:"Deep blue-grey tones reminiscent of still water. A distinctive, premium finish for coastal and contemporary builds." },
          { name:"Eclipse",         img:"assets/img/agg-boral/eclipse.webp",         tone:"Dark Charcoal · Grey",  desc:"Rich dark charcoal with deep grey undertones — a dramatic, near-black finish that seals to a striking wet-look sheen." },
          { name:"Midnight",        img:"assets/img/agg-boral/midnight.webp",        tone:"Very Dark · Charcoal",  desc:"One of the darkest finishes in the Boral range. Near-black when sealed and highly contemporary." },
          { name:"Night Sky",       img:"assets/img/agg-boral/night-sky.webp",       tone:"Black · Dark Fleck",    desc:"Deep black aggregate with scattered dark flecks — like a clear night sky underfoot. Bold and premium." },
          { name:"Black Night",     img:"assets/img/agg-boral/black-night.webp",     tone:"Jet Black",             desc:"The darkest of the Boral range. Pure jet-black aggregate for a high-contrast, ultra-modern finish." },
        ],
      },
      {
        supplier:"Nielsens",
        intro:"Nielsens' range uses locally sourced SEQ aggregate with distinct, memorable colour names. Strong selection of dark, mid and light tones — well suited to the Queensland landscape and all property styles.",
        mixes:[
          { name:"Oyster",      img:"assets/img/agg-nielsens/oyster.webp",      tone:"Cream · Off-White",      desc:"Soft cream and oyster tones — light, coastal and versatile. Popular on driveways, paths and pool surrounds." },
          { name:"Panda",       img:"assets/img/agg-nielsens/panda.webp",       tone:"Black · White",           desc:"Bold black and white contrast aggregate. A clean, contemporary alternative to the classic salt and pepper." },
          { name:"Marble",      img:"assets/img/agg-nielsens/marble.webp",      tone:"White · Light Grey",      desc:"Light grey and white tones with a refined look — reminiscent of natural marble. Suits rendered and modern homes." },
          { name:"Praline",     img:"assets/img/agg-nielsens/praline.webp",     tone:"Warm Caramel · Brown",    desc:"Warm caramel and brown tones — earthy and inviting. Complements timber, brick and Queenslander-style homes." },
          { name:"Lamington",   img:"assets/img/agg-nielsens/lamington.webp",   tone:"Chocolate · Cream",       desc:"Rich chocolate-brown with cream variation. A warm, characterful finish for driveways and entertaining areas." },
          { name:"Tim Tam",     img:"assets/img/agg-nielsens/tim-tam.webp",     tone:"Deep Brown · Chocolate",  desc:"Deep, rich brown tones — bold and warm. One of the most popular earthy choices in the Nielsens range." },
          { name:"Brindle",     img:"assets/img/agg-nielsens/brindle.webp",     tone:"Mixed Brown · Tan",       desc:"Mixed brindle tones of tan and brown — naturally varied and organic-looking. Great for acreage and rural driveways." },
          { name:"Granite Bay",  img:"assets/img/agg-nielsens/granite-bay.webp", tone:"Grey · Granite",         desc:"Natural granite grey tones with the texture and depth of real stone. A timeless, premium finish." },
          { name:"Flintstone",  img:"assets/img/agg-nielsens/flintstone.webp",  tone:"Flint Grey · Mixed",      desc:"Cool grey flint aggregate with natural mixed tones — strong, understated and very versatile." },
          { name:"Stanley",     img:"assets/img/agg-nielsens/stanley.webp",     tone:"Mid Grey · Natural",      desc:"Mid-tone natural grey — reliable, clean and suits almost any home style or landscape." },
          { name:"Manning",     img:"assets/img/agg-nielsens/manning.webp",     tone:"Earthy Natural · Stone",  desc:"Warm natural stone tones sourced from local SEQ quarries. Earthy and grounded — suits the Queensland landscape." },
          { name:"Reserve",     img:"assets/img/agg-nielsens/reserve.webp",     tone:"Premium Mixed · Stone",   desc:"A premium mixed-stone blend with natural colour variation — refined and distinctive on large driveway and patio areas." },
          { name:"Yarrabilba",  img:"assets/img/agg-nielsens/yarrabilba.webp",  tone:"Warm Earth · Local Stone",desc:"Named after the local region — warm earthy tones from SEQ-sourced aggregate. Natural and on-place." },
          { name:"Magpie",      img:"assets/img/agg-nielsens/magpie.webp",      tone:"Black · White · Grey",    desc:"Bold black and white with grey variation — a striking, high-contrast finish with real character." },
          { name:"Orio",        img:"assets/img/agg-nielsens/orio.webp",        tone:"Dark · Black · White",    desc:"Dark aggregate with sharp black and white contrast — bold and contemporary. A strong choice for modern driveways." },
          { name:"Midnight",    img:"assets/img/agg-nielsens/midnight.webp",    tone:"Very Dark · Near Black",  desc:"Deep, near-black finish that seals to a rich wet-look sheen. Premium and dramatic." },
          { name:"Guinness",    img:"assets/img/agg-nielsens/guinness.webp",    tone:"Dark Black · Brown",      desc:"Near-black with warm dark-brown tones — rich, bold and distinctive. Like the drink: dark with depth." },
          { name:"Eclipse",     img:"assets/img/agg-nielsens/eclipse.webp",     tone:"Dark Charcoal · Mixed",   desc:"Deep charcoal aggregate with mixed dark tones — a premium, moody finish suited to contemporary architecture." },
          { name:"Leopard",     img:"assets/img/agg-nielsens/leopard.webp",     tone:"Mixed · Spotted Pattern", desc:"Mixed aggregate with natural spotted-pattern variation — unique, organic and a real talking point." },
          { name:"Magnum",      img:"assets/img/agg-nielsens/magnum.webp",      tone:"Dark Chocolate · Black",  desc:"Dark chocolate and near-black tones — rich and indulgent. A bold premium finish for standout driveways." },
        ],
      },
    ],
    steps:[
      {t:"Choose the blend", d:"Pick your stone and grout colour from the Boral and Nielsens ranges — we'll walk you through both at the site visit."},
      {t:"Pour & place",     d:"Lay the aggregate mix and float it to a tight, even surface."},
      {t:"Time the wash",    d:"Apply surface retarder and wash back at the exact window to reveal the stone."},
      {t:"Seal & protect",   d:"Acid wash, then build up seal coats for the finished sheen."},
    ],
    faqs:[
      {q:"What's the difference between Boral and Nielsens ranges?",  a:"Boral tend toward more consistent fine aggregates with strong colour options. Nielsens use locally sourced stone with more natural variation in size and tone. We'll walk you through both ranges at your site visit so you can compare in real light."},
      {q:"Is it slippery when wet?",          a:"Less than smooth concrete — the exposed stone gives natural grip, which is why it's popular around pools."},
      {q:"How often does it need resealing?", a:"Every 2–3 years for a driveway to keep the wet-look and stain resistance. It's a quick job."},
      {q:"Can you do a small area?",          a:"Yes — entries, paths and pool surrounds are some of our favourite exposed aggregate jobs."},
      {q:"Can I see the stone before we commit?", a:"Always. We'll walk through your colour options at the site visit so you can choose in your actual daylight conditions before a drop of concrete is poured."},
    ],
    stat:["Boral & Nielsens","Choose your stone","Wet-look seal"],
    testimonial:{ q:"Straight answers, fixed price, turned up when they said. The aggregate finish is a different league.", n:"Mark L.", r:"Strathpine" },
  },

  /* 13 ── COLOURED CONCRETE ───────────────────────────────────────── */
  {
    id:"coloured", name:"Coloured", short:"Coloured",
    metaDesc:"Coloured concrete across South East QLD. Full-depth iron oxide pigments — Boral & Nielsens ranges. UV stable, any finish. Owner-operated, fixed price. Based in Morayfield.",
    tag:"Integral oxide colours that go all the way through the slab — not just on the surface.",
    hero:"assets/img/coloured6.webp", pos:"center 55%",
    intro:"Coloured concrete uses iron oxide pigments mixed into the pour, so the colour is through the full depth of the slab — not a coating that wears off. Paired with the right finish and sealer, it lifts a plain grey slab into something that actually adds to the property.",
    benefits:[
      {icon:"sparkle",  t:"Full-depth colour",  d:"Oxide pigment through the whole slab — chips and wear don't expose bare grey underneath."},
      {icon:"check",    t:"UV stable",           d:"Iron oxides don't fade in Queensland sun. The colour holds over time, especially when resealed."},
      {icon:"trowel",   t:"Wide palette",        d:"Charcoals, creams, terracottas, slate blues and more — we'll bring samples to match your home."},
      {icon:"path",     t:"Any finish on top",   d:"Broom, swirl, exposed or honed — the colour works with any surface treatment."},
    ],
    gallery:["assets/img/coloured1.webp","assets/img/coloured2.webp","assets/img/coloured3.webp","assets/img/coloured4.webp","assets/img/coloured5.webp","assets/img/coloured6.webp","assets/img/coloured7.webp","assets/img/coloured8.webp"],
    galleryLabels:["Shadow — Nielsens","Charcoal — Nielsens","Grey Mist — Boral","Grey Mist — Boral","Grey Mist — Boral","Grey Mist — Boral","Onyx — Nielsens","Emperor Colour — Nielsens"],
    steps:[
      {t:"Choose your colour", d:"We bring oxide samples and lay test boards against your home's exterior."},
      {t:"Mix & pour",         d:"Oxide dosed accurately into the truck — consistency across the whole pour."},
      {t:"Finish & cut",       d:"Broom, swirl or texture to your chosen surface; saw-cut control joints."},
      {t:"Seal",               d:"High-quality sealer to lock in the colour and protect from staining."},
    ],
    faqs:[
      {q:"Will the colour fade?",               a:"Not significantly. Oxide pigments are UV-stable. A reseal every few years keeps the colour rich and protected."},
      {q:"Can you match my existing concrete?", a:"We can get close but not exact — concrete colour varies with batch, age and weathering. We'll be upfront about that."},
      {q:"Is it more expensive than plain?",    a:"Slightly — oxide pigment adds cost, but it's a fraction of the price difference between concrete and pavers."},
    ],
    stat:["Full-depth colour","UV stable","Wide palette"],
    testimonial:{ q:"The charcoal coloured driveway lifted the whole streetscape. Looks exactly like the sample — really happy.", n:"Lisa & David W.", r:"Redcliffe" },
    colourRanges:[
      {
        supplier:"Boral",
        intro:"Boral's Colori oxide range delivers consistent, reliable colour batching across the full slab. We use Boral oxides regularly — the colour is dosed accurately into the truck so every pour lands exactly where it should.",
        mixes:[
          { name:"Tungsten",      hex:"#6b7280", img:"assets/img/coloured-boral/tungsten.webp",     desc:"Cool silver-grey — strong and contemporary. Popular on modern rendered homes and commercial slabs." },
          { name:"Frost",         hex:"#e8eae9", img:"assets/img/coloured-boral/frost.webp",        desc:"Very light cool grey — almost white. Clean and minimal, suits coastal and Hamptons-style builds." },
          { name:"Silver",        hex:"#b8bec4", img:"assets/img/coloured-boral/silver.webp",       desc:"Light neutral grey with a cool tone. Versatile and understated across most exterior styles." },
          { name:"Coconut",       hex:"#f0e8d8", img:"assets/img/coloured-boral/coconut.webp",      desc:"Warm off-white with a soft cream base. Bright and airy — great for alfresco and pool surrounds." },
          { name:"Canvas",        hex:"#eae0c8", img:"assets/img/coloured-boral/canvas.webp",       desc:"Warm neutral cream. A natural, relaxed tone that complements timber, brick and rendered finishes." },
          { name:"Mint Green",    hex:"#c8d8c8", img:"assets/img/coloured-boral/mint-green.webp",   desc:"Soft sage-green with a cool, natural feel. A distinctive, landscape-connected choice for outdoor areas." },
          { name:"Café",          hex:"#9a7858", img:"assets/img/coloured-boral/cafe.webp",         desc:"Warm medium brown — earthy and grounded. Works beautifully in acreage and bush settings." },
          { name:"Turmeric",      hex:"#d4a030", img:"assets/img/coloured-boral/turmeric.webp",     desc:"Bold golden yellow — rich and warm. A standout tone that catches the Queensland sun." },
          { name:"Maize",         hex:"#e0b848", img:"assets/img/coloured-boral/maize.webp",        desc:"Warm golden yellow, softer than Turmeric. Natural and inviting for paths and outdoor entertaining." },
          { name:"Sandstone",     hex:"#c8a878", img:"assets/img/coloured-boral/sandstone.webp",    desc:"Classic sandy tan — one of the most popular neutrals. Warm, natural and suits every property style." },
          { name:"Latte",         hex:"#c8a080", img:"assets/img/coloured-boral/latte.webp",        desc:"Light caramel — warm and welcoming. A refined, easy-living tone for patios and entertaining areas." },
          { name:"Linseed",       hex:"#c0a060", img:"assets/img/coloured-boral/linseed.webp",      desc:"Warm golden tan with olive undertones. Earthy and sophisticated — suits character and heritage homes." },
          { name:"Olive",         hex:"#787840", img:"assets/img/coloured-boral/olive.webp",        desc:"Rich olive green — bold and earthy. A strong landscape colour for rural and acreage properties." },
          { name:"Mushroom",      hex:"#a89080", img:"assets/img/coloured-boral/mushroom.webp",     desc:"Warm grey-brown — the classic neutral. Versatile, timeless and works with almost any exterior palette." },
          { name:"Toffee",        hex:"#a87848", img:"assets/img/coloured-boral/toffee.webp",       desc:"Medium caramel brown — warm and sweet. A popular choice for driveways and paths in brick homes." },
          { name:"Hazelnut",      hex:"#b89068", img:"assets/img/coloured-boral/hazelnut.webp",     desc:"Light hazel brown — soft and natural. Complements timber, sandstone and Queenslander-style homes." },
          { name:"Orange Cream",  hex:"#e0a070", img:"assets/img/coloured-boral/orange-cream.webp", desc:"Soft warm orange — light and inviting. A gentle take on the terracotta family." },
          { name:"Spice",         hex:"#c06838", img:"assets/img/coloured-boral/spice.webp",        desc:"Warm red-orange spice tone. Earthy and vibrant — grounds outdoor areas with real character." },
          { name:"Terracotta",    hex:"#bc6040", img:"assets/img/coloured-boral/terracotta.webp",   desc:"The classic earthy orange-red. A perennial favourite that suits traditional and Queenslander-style homes." },
          { name:"Tuscan Clay",   hex:"#a85838", img:"assets/img/coloured-boral/tuscan-clay.webp",  desc:"Deeper Tuscan terracotta — rich and Mediterranean. A bold, confident choice for entries and driveways." },
          { name:"Burnt Orange",  hex:"#a84820", img:"assets/img/coloured-boral/burnt-orange.webp", desc:"Deep burnt orange-red. Strong and earthy — makes a statement on driveways and alfresco areas." },
          { name:"Desert Red",    hex:"#983020", img:"assets/img/coloured-boral/desert-red.webp",   desc:"Earthy desert red — warm and rugged. Pairs naturally with sandstone, timber and native landscaping." },
          { name:"Cacao",         hex:"#6a3020", img:"assets/img/coloured-boral/cacao.webp",        desc:"Deep chocolate-brown — rich, earthy and premium. Seals to a beautiful dark wet-look finish." },
          { name:"Charcoal",      hex:"#484c50", img:"assets/img/coloured-boral/charcoal.webp",     desc:"Dark charcoal grey — the most requested contemporary colour. Strong and modern, pairs with any exterior." },
          { name:"Blue Steel",    hex:"#5a6878", img:"assets/img/coloured-boral/blue-steel.webp",   desc:"Cool blue-grey steel tone. A sophisticated, industrial-inspired choice for modern architecture." },
          { name:"Grey Mist",     hex:"#c0c8d0", img:"assets/img/coloured-boral/grey-mist.webp",   desc:"Light cool grey with a slight blue tint. Fresh and contemporary — suits rendered and modern homes." },
          { name:"Oracle",        hex:"#6a7080", img:"assets/img/coloured-boral/oracle.webp",       desc:"Medium grey-purple — subtle and refined. An elegant neutral for sophisticated exterior palettes." },
          { name:"Moonlight",     hex:"#a0b0c0", img:"assets/img/coloured-boral/moonlight.webp",   desc:"Soft blue-grey — light and calm. A coastal, relaxed tone for pool surrounds and alfresco slabs." },
          { name:"Indian Ink",    hex:"#202830", img:"assets/img/coloured-boral/indian-ink.webp",   desc:"Very dark navy-black. Deep and dramatic — a premium choice for high-contrast contemporary builds." },
          { name:"Graphite",      hex:"#404850", img:"assets/img/coloured-boral/graphite.webp",     desc:"Dark graphite grey with a cool, sophisticated finish. One of Boral's most popular modern shades." },
          { name:"Jet Black",     hex:"#181a1c", img:"assets/img/coloured-boral/jet-black.webp",    desc:"Pure jet black — the deepest tone in the range. Seals to a dramatic, ultra-modern wet-look finish." },
          { name:"Emperor",       hex:"#202224", img:"assets/img/coloured-boral/emperor.webp",      desc:"Near-black with a deep richness. A premium, distinctive finish for standout driveways and entries." },
        ],
      },
      {
        supplier:"Nielsens",
        intro:"Nielsens' Colourmix (by Oxerra) range is well suited to the Queensland climate with a wide selection of earthy, natural and bold tones. Reliable colour consistency across pours — popular across SEQ residential and acreage builds.",
        mixes:[
          { name:"Suede",         hex:"#c0a880", img:"assets/img/coloured-nielsens/suede.webp",        desc:"Warm sandy tan — natural and relaxed. A versatile neutral that suits most home styles across SEQ." },
          { name:"Ginger",        hex:"#c07840", img:"assets/img/coloured-nielsens/ginger.webp",       desc:"Warm amber-ginger brown. Rich and inviting — a natural complement to timber and brick exteriors." },
          { name:"Havana",        hex:"#783820", img:"assets/img/coloured-nielsens/havana.webp",       desc:"Deep tobacco brown. Rich, earthy and premium — seals to a beautiful dark wet-look sheen." },
          { name:"Jabiru",        hex:"#3a2818", img:"assets/img/coloured-nielsens/jabiru.webp",       desc:"Very dark brown-black. One of the deepest earthy tones — bold and distinctive." },
          { name:"Cappuccino",    hex:"#a07858", img:"assets/img/coloured-nielsens/cappuccino.webp",   desc:"Medium warm brown — the classic café tone. Versatile and popular for driveways and outdoor areas." },
          { name:"Sandstone",     hex:"#c8a878", img:"assets/img/coloured-nielsens/sandstone.webp",   desc:"Classic sandy tan. One of the most popular neutrals — warm, natural and suits every property style." },
          { name:"Taupe",         hex:"#a89880", img:"assets/img/coloured-nielsens/taupe.webp",        desc:"Warm grey-brown taupe — the universal neutral. Complements every exterior palette." },
          { name:"Flint",         hex:"#888888", img:"assets/img/coloured-nielsens/flint.webp",        desc:"Mid cool grey — clean and understated. A reliable contemporary choice for modern homes." },
          { name:"Frost",         hex:"#e8eae9", img:"assets/img/coloured-nielsens/frost.webp",        desc:"Very light cool grey — bright and clean. Suits coastal, Hamptons and contemporary exterior styles." },
          { name:"Dolomite",      hex:"#d8d0c0", img:"assets/img/coloured-nielsens/dolomite.webp",    desc:"Pale off-white mineral tone. Natural and refined — a sophisticated light base colour." },
          { name:"Silk",          hex:"#eae4d8", img:"assets/img/coloured-nielsens/silk.webp",         desc:"Very light warm cream. Soft and elegant — great for alfresco, pool surrounds and entertaining areas." },
          { name:"Soapstone",     hex:"#d8d8d0", img:"assets/img/coloured-nielsens/soapstone.webp",   desc:"Light grey-white with a cool base. Clean and minimal for contemporary and Hamptons-style builds." },
          { name:"Arctic",        hex:"#f0f0f0", img:"assets/img/coloured-nielsens/arctic.webp",       desc:"Near-white — the lightest tone in the range. Bright and airy for light-filled outdoor spaces." },
          { name:"Shadow",        hex:"#888898", img:"assets/img/coloured-nielsens/shadow.webp",       desc:"Medium cool grey with a slight blue cast. Contemporary and calm — popular on rendered homes." },
          { name:"Silver",        hex:"#b8bec4", img:"assets/img/coloured-nielsens/silver.webp",       desc:"Light neutral silver-grey. Versatile and understated across all exterior styles." },
          { name:"Platinum",      hex:"#c8ccd0", img:"assets/img/coloured-nielsens/platinum.webp",    desc:"Light silver-grey — refined and premium. A sophisticated neutral for high-end residential builds." },
          { name:"Onyx",          hex:"#282828", img:"assets/img/coloured-nielsens/onyx.webp",          desc:"Very dark near-black. Deep and dramatic — a premium choice for contemporary architecture." },
          { name:"Black Knight",  hex:"#1a1e20", img:"assets/img/coloured-nielsens/black-knight.webp", desc:"Near-black with a cool base. Bold and distinctive — makes a strong statement on driveways and entries." },
          { name:"Charcoal",      hex:"#484c50", img:"assets/img/coloured-nielsens/charcoal.webp",     desc:"Dark charcoal grey — one of the most requested contemporary colours. Strong, modern and versatile." },
          { name:"Bluestone",     hex:"#3a4858", img:"assets/img/coloured-nielsens/bluestone.webp",    desc:"Cool dark grey-blue — a nod to classic bluestone paving. Contemporary and architectural." },
          { name:"Black",         hex:"#101010", img:"assets/img/coloured-nielsens/black.webp",        desc:"Pure black — the deepest tone. Seals to a striking, ultra-modern wet-look finish." },
          { name:"Emperor",       hex:"#202224", img:"assets/img/coloured-nielsens/emperor.webp",      desc:"Near-black with depth and richness. A premium, distinctive finish for standout driveways." },
          { name:"Jet Black",     hex:"#181a1c", img:"assets/img/coloured-nielsens/jet-black.webp",    desc:"Jet black — dramatic and bold. Seals to a stunning high-contrast finish for contemporary builds." },
          { name:"Black Velvet",  hex:"#181620", img:"assets/img/coloured-nielsens/black-velvet.webp", desc:"Deep black with a rich, velvety tone. The ultimate dark finish — premium and architectural." },
          { name:"Pumpkin",       hex:"#d06828", img:"assets/img/coloured-nielsens/pumpkin.webp",     desc:"Bold warm orange — vibrant and earthy. A confident, characterful choice for entries and paths." },
          { name:"Turmeric",      hex:"#d0a030", img:"assets/img/coloured-nielsens/turmeric.webp",    desc:"Rich golden yellow. Bold and warm — a strong landscape colour that catches the Queensland sun." },
          { name:"Ravine",        hex:"#a09070", img:"assets/img/coloured-nielsens/ravine.webp",       desc:"Warm earthy stone tone — natural and grounded. Blends effortlessly with the Queensland landscape." },
          { name:"Desert Red",    hex:"#983020", img:"assets/img/coloured-nielsens/desert-red.webp",  desc:"Earthy desert red — warm and rugged. Pairs naturally with sandstone, timber and native gardens." },
          { name:"Limestone",     hex:"#d6c4a0", img:"assets/img/coloured-nielsens/limestone.webp",   desc:"Pale limestone cream with natural warmth. Refined and versatile across all residential styles." },
          { name:"Sepia",         hex:"#907050", img:"assets/img/coloured-nielsens/sepia.webp",        desc:"Warm sepia brown — a classic earthy tone. Rich and natural, suits Queenslander and heritage homes." },
          { name:"Peppercorn",    hex:"#585048", img:"assets/img/coloured-nielsens/peppercorn.webp",  desc:"Dark grey-brown — earthy and grounded. A sophisticated alternative to standard charcoal." },
          { name:"Venetian",      hex:"#b84830", img:"assets/img/coloured-nielsens/venetian.webp",    desc:"Warm Venetian terracotta-red. Mediterranean-inspired and bold — great for driveways and entries." },
          { name:"Fremantle",     hex:"#b09068", img:"assets/img/coloured-nielsens/fremantle.webp",   desc:"Warm earthy tan — a nod to WA sandstone. Natural and relaxed for outdoor entertaining areas." },
          { name:"Horizon",       hex:"#6878a0", img:"assets/img/coloured-nielsens/horizon.webp",     desc:"Muted blue-grey — calm and coastal. A distinctive, sophisticated choice for pool surrounds and slabs." },
          { name:"Vesuvius",      hex:"#604838", img:"assets/img/coloured-nielsens/vesuvius.webp",    desc:"Deep volcanic brown. Rich and earthy — a premium dark tone for acreage and character homes." },
          { name:"Everglade",     hex:"#4a6040", img:"assets/img/coloured-nielsens/everglade.webp",   desc:"Deep forest green — bold and natural. A unique landscape-connected choice for outdoor areas." },
          { name:"Papyrus",       hex:"#d8c898", img:"assets/img/coloured-nielsens/papyrus.webp",     desc:"Warm parchment — light and natural. A refined neutral that sits beautifully in garden settings." },
          { name:"Arizona",       hex:"#b86048", img:"assets/img/coloured-nielsens/arizona.webp",     desc:"Warm dusty terracotta-red. Sun-baked and earthy — a strong tone for driveways and entries." },
          { name:"Colonial Red",  hex:"#983828", img:"assets/img/coloured-nielsens/colonial-red.webp",desc:"Classic brick red. A timeless colour for traditional homes, paths and outdoor entertaining areas." },
          { name:"Leaf Green",    hex:"#6a8840", img:"assets/img/coloured-nielsens/leaf-green.webp",  desc:"Natural leaf green — fresh and organic. A standout landscape colour for garden-connected spaces." },
          { name:"Aztec",         hex:"#a06030", img:"assets/img/coloured-nielsens/aztec.webp",         desc:"Warm earthy brown-orange. Bold and grounded — suits acreage, rural and character properties." },
          { name:"Spice",         hex:"#c06838", img:"assets/img/coloured-nielsens/spice.webp",         desc:"Warm red-orange spice tone. Vibrant and earthy — grounds outdoor areas with real character." },
          { name:"Red Rock",      hex:"#983028", img:"assets/img/coloured-nielsens/red-rock.webp",      desc:"Deep earthy red — bold and rugged. A natural, confident choice for driveways and paths." },
          { name:"Marl",          hex:"#a8b0a0", img:"assets/img/coloured-nielsens/marl.webp",          desc:"Light grey-green — soft and natural. A calm, landscape-connected neutral for outdoor slabs." },
          { name:"Pumice",        hex:"#c0b8a8", img:"assets/img/coloured-nielsens/pumice.webp",        desc:"Light stone-grey with a warm base. Natural and understated — suits bush and acreage settings." },
          { name:"Cargo",         hex:"#a08060", img:"assets/img/coloured-nielsens/cargo.webp",         desc:"Warm tan-brown — earthy and versatile. A reliable, natural tone across most residential styles." },
          { name:"Terracotta",    hex:"#bc6040", img:"assets/img/coloured-nielsens/terracotta.webp",    desc:"Classic earthy orange-red. A perennial SEQ favourite that suits traditional and Queenslander homes." },
          { name:"Caribbean Blue",hex:"#4898b8", img:"assets/img/coloured-nielsens/caribbean-blue.webp",desc:"Aqua blue — vibrant and tropical. A bold, unique choice for pool surrounds and alfresco areas." },
        ],
      },
    ],
  },

  /* 14 ── STAMPED CONCRETE ────────────────────────────────────────── */
  {
    id:"stamped", name:"Stamped", short:"Stamped",
    metaDesc:"Stamped concrete across South East QLD. 3D texture in cobblestone, slate, flagstone & more. Colour hardener & contrast release. Fixed price. Based in Morayfield.",
    tag:"3D texture pressed into fresh concrete — pavers, slate and stone looks in one solid pour.",
    hero:"assets/img/stamped-hero.webp", pos:"center",
    intro:"Stamped concrete uses rigid polyurethane mats pressed into the surface while the concrete is still workable, leaving a 3D impression of stone, slate, cobble or tile. The result has physical depth and texture that stencilling can't replicate — and it's all one unjointed slab.",
    benefits:[
      {icon:"trowel",    t:"Real physical depth",       d:"Stamps create genuine 3D relief in the surface — not just a printed pattern but actual texture you can feel."},
      {icon:"sparkle",   t:"Wide pattern selection",    d:"Ashlar slate, random stone, cobblestone, wood plank, Versailles tile — most popular paving patterns available as stamps."},
      {icon:"check",     t:"Colour hardener + release", d:"Colour hardener sets the base tone; release agent applied over the stamp creates contrast in the recessed lines."},
      {icon:"path",      t:"One solid surface",         d:"All the look of pavers or stone with no joints to weed, no pieces to lift and no ants nesting underneath."},
    ],
    steps:[
      {t:"Choose pattern & colour",  d:"Select the stamp mat, base colour hardener and highlight release agent from samples."},
      {t:"Pour & colour",            d:"Place the slab, broadcast colour hardener and trowel to the correct stage."},
      {t:"Stamp the surface",        d:"Lay mats in sequence and press the pattern into the concrete before it sets."},
      {t:"Wash, detail & seal",      d:"Wash off the release agent to reveal contrast, cut control joints and apply sealer."},
    ],
    faqs:[
      {q:"How is stamped different from stencilled?",   a:"Stamped creates a physical 3D impression in the concrete — actual relief in the surface. Stencil applies colour and pattern but the surface stays flat."},
      {q:"Does it crack at the pattern lines?",         a:"The stamp lines aren't structural weak points — we still saw-cut control joints at the correct spacing independent of the pattern."},
      {q:"Can you stamp an existing slab?",             a:"Not directly — stamps go into fresh concrete. We can apply a stamped overlay to an existing sound slab, but it's a different process."},
    ],
    stat:["3D relief texture","Colour + highlight","No joints"],
    testimonial:{ q:"The stamped cobblestone patio looks incredible — everyone thinks it's real stone until they look closely.", n:"Megan & Dave P.", r:"Albany Creek" },
    stampPatterns:[
      { name:"London Cobble",              img:"assets/img/stamped/london-cobble.webp",       desc:"Classic rounded cobblestone texture — the most popular stamp pattern. Authentic aged-stone look for driveways, entries and paths." },
      { name:"Ashlar Slate",               img:"assets/img/stamped/ashlar-slate.webp",        desc:"Large-format slate tiles in a random ashlar layout. Contemporary and clean — suits modern rendered and Hamptons-style homes." },
      { name:"Flagstone",                  img:"assets/img/stamped/flagstone.webp",           desc:"Large irregular flag-stone pieces with natural variation. A high-end, relaxed look for patios and pool surrounds." },
      { name:"Walkway Slate",              img:"assets/img/stamped/walkway-slate.webp",       desc:"Narrow slate-format pattern ideal for paths, walkways and side access areas. Clean and directional." },
      { name:"Seamless",                   img:"assets/img/stamped/seamless.webp",            desc:"Continuous texture without visible joints. Grippy and refined — ideal for pool surrounds and wet alfresco areas." },
      { name:"Timber Deck",                img:"assets/img/stamped/timber-deck.webp",         desc:"Timber board texture that captures the warmth of wood in a durable concrete surface. Great under pergolas and outdoor rooms." },
      { name:"Bushrock (Crazy Stone)",     img:"assets/img/stamped/bushrock.webp",            desc:"Natural irregular crazy-stone effect — earthy and organic. Popular for garden paths, pool surrounds and outdoor entertaining." },
      { name:"Flemish",                    img:"assets/img/stamped/flemish.webp",             desc:"Classic Flemish brick pattern with a slightly irregular, hand-laid character. Timeless and versatile for any outdoor area." },
      { name:"Antique Brick Straight",     img:"assets/img/stamped/antique-brick-straight.webp", desc:"Traditional straight-set brick with an aged, textured surface. A reliable classic that suits brick homes and heritage streetscapes." },
      { name:"Antique Brick Curved Border",img:"assets/img/stamped/antique-brick-curved.webp",   desc:"Curved brick border pattern — ideal for framing feature areas, driveways and garden edges with a traditional look." },
      { name:"Brindabella",                img:"assets/img/stamped/brindabella.webp",         desc:"Natural stone-look with soft irregular edges and subtle surface variation. Relaxed and organic — suits acreage and bush settings." },
      { name:"Regal",                      img:"assets/img/stamped/regal.webp",               desc:"Bold, formal stone pattern with strong lines and generous scale. A premium, architectural choice for entries and entertaining areas." },
    ],
  },

  /* 15 ── COVERCRETE ──────────────────────────────────────────────── */
  {
    id:"covercrete", name:"Covercrete", short:"Covercrete",
    metaDesc:"Covercrete spray overlays across South East QLD. Decorative resurfacing over existing slabs — no demolition. Dulux Avista colours & patterns. Fixed price. Based in Morayfield.",
    tag:"Transform tired concrete with a sprayed decorative overlay — no demolition required.",
    hero:"assets/img/covercrete-hero.webp", pos:"center",
    intro:"Covercrete is a spray-applied polymer-modified overlay that bonds directly to existing sound concrete. You get a fresh, decorative surface without the cost or disruption of a full rip-out — and with a far wider range of finishes than plain resurfacing.",
    benefits:[
      {icon:"sparkle",   t:"No demolition",               d:"Goes over your existing slab if it's structurally sound — no skip bin, no excavation, no mess."},
      {icon:"trowel",    t:"Wide pattern & colour range",  d:"Aggregate, slate, stone and custom textured finishes in dozens of colour options."},
      {icon:"check",     t:"Bonds to the existing slab",   d:"Polymer-modified mix bonds chemically — it won't delaminate if the surface is properly prepared."},
      {icon:"path",      t:"Slip-rated options",           d:"Texture profiles available for pool surrounds, paths and alfresco areas."},
    ],
    gallery:["assets/img/covercrete2.webp","assets/img/pool-deck-tile.webp"],
    galleryLabels:["Cream & White with Quarry Tile Stencil",""],
    steps:[
      {t:"Assess the existing slab", d:"Check for structural cracks, delamination or contamination that needs fixing first."},
      {t:"Prepare the surface",      d:"Grind or acid-etch to open the profile; repair any cracks or spalling."},
      {t:"Apply the base coat",      d:"Spray or trowel the bonding slurry coat to the correct thickness."},
      {t:"Texture, colour & seal",   d:"Apply the finish coat, texture, colour and sealer for the complete result."},
    ],
    faqs:[
      {q:"How thick is it?",         a:"Typically 3–6mm. Enough to carry the finish without building up height at doorways or transitions."},
      {q:"Will it peel off?",        a:"Not if the base is sound and the prep is done right. Delamination almost always comes from inadequate surface prep — we don't skip that step."},
      {q:"How long does it last?",   a:"10–15 years with periodic resealing. Longer if it's in a sheltered area or low-traffic zone."},
    ],
    stat:["No demolition","3–6mm overlay","10–15 yr lifespan"],
    testimonial:{ q:"Our old driveway looked brand new in two days — no mess, no skip, exactly the texture we wanted.", n:"Karen M.", r:"Albany Creek" },
    coverColours:[
      { name:"White",            img:"assets/img/covercrete-colours/white.webp",           desc:"The brightest, cleanest base — great for pool surrounds and light-filled alfresco areas." },
      { name:"Cream",            img:"assets/img/covercrete-colours/cream.webp",           desc:"Soft warm off-white. A timeless neutral that suits rendered and Hamptons-style homes." },
      { name:"Merino",           img:"assets/img/covercrete-colours/merino.webp",          desc:"Warm pale neutral — natural and relaxed. One of the most versatile tones in the range." },
      { name:"Sandy Beige",      img:"assets/img/covercrete-colours/sandy-beige.webp",     desc:"Light sandy beige with a warm undertone. Easy-living and complements most landscaping." },
      { name:"Sandstone",        img:"assets/img/covercrete-colours/sandstone.webp",       desc:"Classic mid sandy tan — earthy and natural. Suits every property style across SEQ." },
      { name:"Bluegum",          img:"assets/img/covercrete-colours/bluegum.webp",         desc:"Soft blue-grey green. A subtle, nature-inspired tone that works beautifully outdoors." },
      { name:"Silver Sands",     img:"assets/img/covercrete-colours/silver-sands.webp",    desc:"Cool light grey with a silver tone. Contemporary and clean for modern rendered homes." },
      { name:"French Grey",      img:"assets/img/covercrete-colours/french-grey.webp",     desc:"Warm mid grey with a slight beige cast. Sophisticated and popular on coastal homes." },
      { name:"Lite Mocha",       img:"assets/img/covercrete-colours/lite-mocha.webp",      desc:"Light warm brown — the classic mocha tone. Relaxed and versatile for outdoor areas." },
      { name:"Bluestone",        img:"assets/img/covercrete-colours/bluestone.webp",       desc:"Cool mid grey-blue. A nod to classic bluestone paving — contemporary and architectural." },
      { name:"Slate Grey",       img:"assets/img/covercrete-colours/slate-grey.webp",      desc:"Mid cool grey. Clean and understated — suits most modern and rendered exteriors." },
      { name:"Granite",          img:"assets/img/covercrete-colours/granite.webp",         desc:"Speckled granite effect — adds visual texture and depth to any outdoor surface." },
      { name:"Chestnut",         img:"assets/img/covercrete-colours/chestnut.webp",        desc:"Warm mid-brown. Rich and earthy — complements timber, brick and native gardens." },
      { name:"Light Terracotta", img:"assets/img/covercrete-colours/light-terracotta.webp",desc:"Soft terracotta — warm and inviting. A lighter take on the classic earthy orange-red." },
      { name:"Brick Red",        img:"assets/img/covercrete-colours/brick-red.webp",       desc:"Warm brick red. Earthy and bold — a strong tone for driveways and entertaining areas." },
      { name:"Dark Terracotta",  img:"assets/img/covercrete-colours/dark-terracotta.webp", desc:"Deep, rich terracotta. Full-bodied and earthy — makes a statement on larger surfaces." },
      { name:"Chocolate",        img:"assets/img/covercrete-colours/chocolate.webp",       desc:"Deep chocolate brown. Rich and premium — seals to a beautiful wet-look sheen." },
      { name:"Charcoal",         img:"assets/img/covercrete-colours/charcoal.webp",        desc:"Dark charcoal grey — the most requested contemporary colour. Strong and modern." },
      { name:"Gunmetal",         img:"assets/img/covercrete-colours/gunmetal.webp",        desc:"Very dark blue-grey. Cool, industrial and distinctive — a premium contemporary finish." },
      { name:"Jet Black",        img:"assets/img/covercrete-colours/jet-black.webp",       desc:"Pure black — the deepest tone. Seals to a dramatic, ultra-modern wet-look finish." },
    ],
    coverPatterns:[
      { name:"Cobblestone",               img:"assets/img/covercrete-stencils/stencil-cobblestone.webp",                  desc:"Classic rounded cobblestone — the most popular stencil pattern for driveways and entries." },
      { name:"English Cobble",            img:"assets/img/covercrete-stencils/stencil-english-cobble.webp",                desc:"Tighter English-style cobble with a dense, traditional feel. Great for period homes." },
      { name:"Cobble Header",             img:"assets/img/covercrete-stencils/stencil-cobble-header.webp",                desc:"Cobble with a decorative header band — adds a framing detail to driveways and paths." },
      { name:"European Fan",              img:"assets/img/covercrete-stencils/stencil-european-fan.webp",                 desc:"Fan-shaped cobble sections radiating outward. A striking European courtyard look." },
      { name:"Brick",                     img:"assets/img/covercrete-stencils/stencil-brick.webp",                        desc:"Standard running-bond brick pattern. Timeless and versatile for any outdoor area." },
      { name:"Rustic Brick",              img:"assets/img/covercrete-stencils/stencil-rustic-brick.webp",                 desc:"Aged, textured brick with a handmade character. Suits heritage and traditional homes." },
      { name:"Convict Brick",             img:"assets/img/covercrete-stencils/stencil-convict-brick.webp",                desc:"Wide-format convict-style brick with bold lines and a colonial Australian feel." },
      { name:"Classic Herringbone",       img:"assets/img/covercrete-stencils/stencil-classic-herringbone.webp",          desc:"Traditional 45° herringbone brick. A classic pattern that suits any home style." },
      { name:"Brick Header Soldier",      img:"assets/img/covercrete-stencils/stencil-brick-header-soldier-course.webp",  desc:"Brick with a soldier-course header detail for a refined, architectural border finish." },
      { name:"Edge Brick Header",         img:"assets/img/covercrete-stencils/stencil-edge-brick-header.webp",            desc:"Edge-set brick header — a clean, formal framing detail for feature areas and entries." },
      { name:"Ashlar Slate",              img:"assets/img/covercrete-stencils/ashlar-slate.webp",                         desc:"Large-format slate tiles in a random ashlar layout. Contemporary and clean." },
      { name:"Flagstone",                 img:"assets/img/covercrete-stencils/stencil-flagstone.webp",                    desc:"Irregular flagstone pieces. A natural, relaxed look for patios and pool surrounds." },
      { name:"Bushrock",                  img:"assets/img/covercrete-stencils/stencil-bushrock.webp",                     desc:"Natural crazy-stone effect — earthy and organic for paths and outdoor entertaining." },
      { name:"Random Bluestone",          img:"assets/img/covercrete-stencils/stencil-random-bluestone.webp",             desc:"Irregular bluestone effect. Cool-toned and contemporary — popular in modern builds." },
      { name:"Antique Tile",              img:"assets/img/covercrete-stencils/antique-tile.webp",                         desc:"Classic aged tile pattern with warm, Mediterranean character." },
      { name:"Large Tile",                img:"assets/img/covercrete-stencils/stencil-large-tile.webp",                    desc:"Bold large-format tile grid. Clean and modern — suits large alfresco and pool areas." },
      { name:"Large Tile Header",         img:"assets/img/covercrete-stencils/stencil-large-tile-header.webp",            desc:"Large tile with a decorative header border detail for a polished finish." },
      { name:"Quarry Tile",               img:"assets/img/covercrete-stencils/stencil-8-quarry-tile.webp",                 desc:"Classic quarry tile pattern — a durable, slip-resistant option for high-traffic areas." },
      { name:"Diamond Tile",              img:"assets/img/covercrete-stencils/stencil-10-diamond-tile.webp",               desc:"Diamond-set tile pattern. Elegant and distinctive for feature entries and patios." },
      { name:"Regal Tile",                img:"assets/img/covercrete-stencils/stencil-regal-tile.webp",                    desc:"Ornate regal tile — a formal, high-end pattern for premium entries and entertaining areas." },
      { name:"Mediterranean",             img:"assets/img/covercrete-stencils/stencil-mediterranean.webp",                 desc:"Warm Mediterranean tile pattern. Character-rich and suited to outdoor living spaces." },
      { name:"Keystone",                  img:"assets/img/covercrete-stencils/stencil-keystone.webp",                     desc:"Interlocking keystone pattern — strong visual structure for driveways and paths." },
      { name:"Keystone Header",           img:"assets/img/covercrete-stencils/stencil-keystone-header.webp",              desc:"Keystone with a header border for a framed, finished look on feature areas." },
      { name:"Basket Weave",              img:"assets/img/covercrete-stencils/basket-weave.webp",                         desc:"Woven brick basket-weave pattern. Tactile and traditional — suits cottage and period homes." },
      { name:"Block",                     img:"assets/img/covercrete-stencils/stencil-block.webp",                        desc:"Clean block pattern with a bold, graphic look. Minimal and contemporary." },
      { name:"Star & Compass",            img:"assets/img/covercrete-stencils/stencil-star-compass.webp",                 desc:"Decorative star and compass motif. A standout feature pattern for entries and courtyards." },
      { name:"Rosette",                   img:"assets/img/covercrete-stencils/stencil-rosette.webp",                      desc:"Circular rosette motif — a premium decorative insert for feature entries and courtyards." },
    ],
  },

];

/* share Dulux Avista colours & patterns with resurfacing */
(function(){
  const cc = window.PC_SERVICES.find(s=>s.id==="covercrete");
  const rs = window.PC_SERVICES.find(s=>s.id==="resurfacing");
  rs.coverColours  = cc.coverColours;
  rs.coverPatterns = cc.coverPatterns;
})();
